"""enforce_tenant_isolation

Revision ID: 1f36108742ee
Revises: a5720d19044d
Create Date: 2026-06-13 16:30:08.025245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_policy import PGPolicy
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '1f36108742ee'
down_revision: Union[str, Sequence[str], None] = 'a5720d19044d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_assets_id_workspace', 'assets', ['id', 'workspace_id'])
    op.create_unique_constraint('uq_contacts_id_workspace', 'contacts', ['id', 'workspace_id'])

    public_assets_assets_tenant_isolation_policy = PGPolicy(
        schema="public",
        signature="assets_tenant_isolation_policy",
        on_entity="public.assets",
        definition="FOR ALL\n        USING (workspace_id = NULLIF(current_setting('app.current_workspace_id', true), '')::uuid)"
    )
    op.create_entity(public_assets_assets_tenant_isolation_policy)

    public_contacts_contacts_tenant_isolation_policy = PGPolicy(
        schema="public",
        signature="contacts_tenant_isolation_policy",
        on_entity="public.contacts",
        definition="FOR ALL\n        USING (workspace_id = NULLIF(current_setting('app.current_workspace_id', true), '')::uuid)"
    )
    op.create_entity(public_contacts_contacts_tenant_isolation_policy)

    op.drop_constraint(op.f('asset_consult_log_asset_id_fkey'), 'asset_consult_log', type_='foreignkey')
    op.create_foreign_key(None, 'asset_consult_log', 'assets', ['asset_id', 'workspace_id'], ['id', 'workspace_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('asset_contacts_contact_id_fkey'), 'asset_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'asset_contacts', 'contacts', ['contact_id', 'workspace_id'], ['id', 'workspace_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_contacts_id_workspace', 'contacts', type_='unique')
    op.drop_constraint('uq_assets_id_workspace', 'assets', type_='unique')
    op.drop_constraint(None, 'asset_contacts', type_='foreignkey')
    op.create_foreign_key(op.f('asset_contacts_contact_id_fkey'), 'asset_contacts', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'asset_consult_log', type_='foreignkey')
    op.create_foreign_key(op.f('asset_consult_log_asset_id_fkey'), 'asset_consult_log', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    public_contacts_contacts_tenant_isolation_policy = PGPolicy(
        schema="public",
        signature="contacts_tenant_isolation_policy",
        on_entity="public.contacts",
        definition="FOR ALL\n        USING (workspace_id = NULLIF(current_setting('app.current_workspace_id', true), '')::uuid)"
    )
    op.drop_entity(public_contacts_contacts_tenant_isolation_policy)

    public_assets_assets_tenant_isolation_policy = PGPolicy(
        schema="public",
        signature="assets_tenant_isolation_policy",
        on_entity="public.assets",
        definition="FOR ALL\n        USING (workspace_id = NULLIF(current_setting('app.current_workspace_id', true), '')::uuid)"
    )
    op.drop_entity(public_assets_assets_tenant_isolation_policy)

    # ### end Alembic commands ###
