"""init_db

Revision ID: 58952fad4002
Revises:
Create Date: 2026-06-13 00:16:56.022141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58952fad4002'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Enable pg_trgm
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm";')

    # Create workspaces table without foreign key constraints
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('workspace_name', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.Enum('TRIAL', 'STARTER', 'BUSINESS', 'ENTERPRISE', name='subscriptionplan', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )

    # Create users table with foreign key constraints normally
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EDITOR', 'VIEWER', name='userrole', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_workspace_id', 'users', ['workspace_id'], unique=False)

    # Add workspaces -> users forein key constraints manually
    op.create_foreign_key(
        'fk_workspaces_owner_id_users',
        'workspaces', 'users',  # source table, target table
        ['owner_id'], ['id'],   # source column, target column
        ondelete='RESTRICT', initially='DEFERRED', deferrable=True
    )
    op.create_index('ix_workspaces_owner_id', 'workspaces', ['owner_id'], unique=False)

    op.create_table('agencies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_agencies_workspace_name')
    )
    op.create_index('ix_agencies_workspace_id', 'agencies', ['workspace_id'], unique=False)
    op.create_table('asset_tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'tag', name='uq_asset_tags_workspace_tag')
    )
    op.create_index('ix_asset_tags_workspace_id', 'asset_tags', ['workspace_id'], unique=False)
    op.create_table('complexes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_complexes_workspace_name')
    )
    op.create_index('ix_complexes_workspace_id', 'complexes', ['workspace_id'], unique=False)
    op.create_table('contact_tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'tag', name='uq_contact_tags_workspace_tag')
    )
    op.create_index('ix_contact_tags_workspace_id', 'contact_tags', ['workspace_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=8), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_name', 'contacts', ['name'], unique=False)
    op.create_index('ix_contacts_tags', 'contacts', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_contacts_workspace_id', 'contacts', ['workspace_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agents_agency_id', 'agents', ['agency_id'], unique=False)
    op.create_index('ix_agents_workspace_id', 'agents', ['workspace_id'], unique=False)
    op.create_index('ix_agents_workspace_phone', 'agents', ['workspace_id', 'phone'], unique=False)
    op.create_table('contact_phones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('is_opted_out', sa.Boolean(), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_phones_contact_id', 'contact_phones', ['contact_id'], unique=False)
    op.create_index('ix_contact_phones_workspace_phone', 'contact_phones', ['workspace_id', 'phone'], unique=False)
    op.create_table('unit_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('complex_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('type_name', sa.String(length=16), nullable=True),
    sa.Column('area_exclusive', sa.Float(), nullable=True),
    sa.Column('area_exclusive_pyeong', sa.Float(), nullable=True),
    sa.Column('area_total', sa.Float(), nullable=True),
    sa.Column('area_total_pyeong', sa.Float(), nullable=True),
    sa.Column('floor_plan', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complex_id', 'type_name', name='uq_unit_types_complex_type')
    )
    op.create_index('ix_unit_types_complex_id', 'unit_types', ['complex_id'], unique=False)
    op.create_index('ix_unit_types_workspace_id', 'unit_types', ['workspace_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('complex_id', sa.UUID(), nullable=True),
    sa.Column('bld', sa.String(length=32), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('unit_type_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('color', sa.String(length=8), nullable=True),
    sa.Column('intake_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('referring_agent_id', sa.UUID(), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('custom_field', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referring_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_assigned_user_id', 'assets', ['assigned_user_id'], unique=False)
    op.create_index('ix_assets_complex_bld_unit', 'assets', ['complex_id', 'bld', 'unit'], unique=False)
    op.create_index('ix_assets_remarks_trgm', 'assets', ['remarks'], unique=False, postgresql_using='gin', postgresql_ops={'remarks': 'gin_trgm_ops'})
    op.create_index('ix_assets_source_type', 'assets', ['source_type'], unique=False)
    op.create_index('ix_assets_tags', 'assets', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_assets_unit_type_id', 'assets', ['unit_type_id'], unique=False)
    op.create_index('ix_assets_workspace_id', 'assets', ['workspace_id'], unique=False)
    op.create_table('asset_consult_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('consult_log', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_consult_log_asset_id', 'asset_consult_log', ['asset_id'], unique=False)
    op.create_index('ix_asset_consult_log_workspace_id', 'asset_consult_log', ['workspace_id'], unique=False)
    op.create_table('asset_contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'TENANT', 'CO_OWNER', name='contactrole', native_enum=False), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('ownership_share', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'contact_id', 'role', name='uq_asset_contacts_asset_contact_role')
    )
    op.create_index('ix_asset_contacts_asset_id', 'asset_contacts', ['asset_id'], unique=False)
    op.create_index('ix_asset_contacts_contact_id', 'asset_contacts', ['contact_id'], unique=False)
    op.create_index('ix_asset_contacts_workspace_id', 'asset_contacts', ['workspace_id'], unique=False)
    op.create_table('asset_price_options',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SALE', 'JEONSE', 'RENT', 'RENT_SHORT', name='pricetype', native_enum=False), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'type', name='uq_asset_price_options_asset_type')
    )
    op.create_index('ix_asset_price_options_asset_id', 'asset_price_options', ['asset_id'], unique=False)
    op.create_index('ix_asset_price_options_workspace_id', 'asset_price_options', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_price_options_workspace_id', table_name='asset_price_options')
    op.drop_index('ix_asset_price_options_asset_id', table_name='asset_price_options')
    op.drop_table('asset_price_options')
    op.drop_index('ix_asset_contacts_workspace_id', table_name='asset_contacts')
    op.drop_index('ix_asset_contacts_contact_id', table_name='asset_contacts')
    op.drop_index('ix_asset_contacts_asset_id', table_name='asset_contacts')
    op.drop_table('asset_contacts')
    op.drop_index('ix_asset_consult_log_workspace_id', table_name='asset_consult_log')
    op.drop_index('ix_asset_consult_log_asset_id', table_name='asset_consult_log')
    op.drop_table('asset_consult_log')
    op.drop_index('ix_assets_workspace_id', table_name='assets')
    op.drop_index('ix_assets_unit_type_id', table_name='assets')
    op.drop_index('ix_assets_tags', table_name='assets', postgresql_using='gin')
    op.drop_index('ix_assets_source_type', table_name='assets')
    op.drop_index('ix_assets_remarks_trgm', table_name='assets', postgresql_using='gin', postgresql_ops={'remarks': 'gin_trgm_ops'})
    op.drop_index('ix_assets_complex_bld_unit', table_name='assets')
    op.drop_index('ix_assets_assigned_user_id', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_unit_types_workspace_id', table_name='unit_types')
    op.drop_index('ix_unit_types_complex_id', table_name='unit_types')
    op.drop_table('unit_types')
    op.drop_index('ix_contact_phones_workspace_phone', table_name='contact_phones')
    op.drop_index('ix_contact_phones_contact_id', table_name='contact_phones')
    op.drop_table('contact_phones')
    op.drop_index('ix_agents_workspace_phone', table_name='agents')
    op.drop_index('ix_agents_workspace_id', table_name='agents')
    op.drop_index('ix_agents_agency_id', table_name='agents')
    op.drop_table('agents')
    op.drop_index('ix_contacts_workspace_id', table_name='contacts')
    op.drop_index('ix_contacts_tags', table_name='contacts', postgresql_using='gin')
    op.drop_index('ix_contacts_name', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_contact_tags_workspace_id', table_name='contact_tags')
    op.drop_table('contact_tags')
    op.drop_index('ix_complexes_workspace_id', table_name='complexes')
    op.drop_table('complexes')
    op.drop_index('ix_asset_tags_workspace_id', table_name='asset_tags')
    op.drop_table('asset_tags')
    op.drop_index('ix_agencies_workspace_id', table_name='agencies')
    op.drop_table('agencies')

    # Drop foreign key constraints
    op.drop_constraint('fk_workspaces_owner_id_users', 'workspaces', type_='foreignkey')

    # Drop tables
    op.drop_index('ix_workspaces_owner_id', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('ix_users_workspace_id', table_name='users')
    op.drop_table('users')

    # Disable pg_trgm
    op.execute('DROP EXTENSION IF EXISTS "pg_trgm";')

    # ### end Alembic commands ###
