import asyncio
from logging.config import fileConfig
from typing import Any, Literal

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlalchemy.sql.schema import SchemaItem

from alembic import context

from src.core.config import get_settings
from src.models import Base

# AssetLink settings object
settings = get_settings()

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Dynamically inject DATABASE_URL from AssetLink settings
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def include_object(
    obj: SchemaItem,
    name: str | None,
    type_: Literal[
        "table", "column", "index", "unique_constraint",
        "foreign_key_constraint", "check_constraint", "schema", "object"
    ],
    reflected: bool,
    compare_to: Any
) -> bool:
    """Alembic autogenerate filter to prevent dropping required PG extensions."""

    if "Grant" in obj.__class__.__name__:
        return False

    # 1. Exclude all objects containing 'pg_trgm' to prevent conflicts with alembic_utils
    if name and "pg_trgm" in name:
        return False

    # 2. Exclude 'object' type or any custom entities generated by alembic_utils
    if type_ == "object" or (obj.__class__.__name__ in ["PGExtension", "PGView", "PGTrigger"]):
        return False

    return True


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,  # Inject filter for offline mode
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,  # Inject filter for online mode
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """In this scenario we need to create an Engine

    and associate a connection with the context.
    """

    # Explicitly pass connect_args to disable statement caching (required for PGBouncer/RLS issues)
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        connect_args={
            "statement_cache_size": 0,
            "max_cached_statement_lifetime": 0
        }
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()